title: Spytify
project_name: spy-spotify
theme: jekyll-theme-hacker
owner_name: jwallet
description: "Records Spotify to mp3 without ads while it plays and includes media tags to the recorded files"
show_downloads: true
reddit_url: "https://www.reddit.com/r/spytify/"
repository_url: "https://www.github.com/jwallet/spy-spotify/"
repository_download: "https://www.github.com/jwallet/spy-spotify/releases/latest/"
owner_url: "https://www.github.com/jwallet/"
url: "https://jwallet.github.io/spy-spotify/"
logo: "https://raw.githubusercontent.com/jwallet/spy-spotify/master/psd/logo.png"
lang: "en-CA"
exclude: ['faq/', 'LICENSE', 'README.md']
sass:
  sass_dir: _sass
  style: compressed
collections:
  faq:
    output: true
baseurl: /spy-spotify
port: 4000
livereload: true